# Generated by Django 4.1.7 on 2023-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfile',
            name='file_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enfile',
            name='file_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
