# Generated by Django 4.1.7 on 2023-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0002_enfile_file_text_alter_enfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfile',
            name='file_text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
