# Generated by Django 4.1.7 on 2023-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0005_remove_enfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfile',
            name='file_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
